language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
- psql -c 'CREATE DATABASE "teamwork-test";' -U postgres
- psql -c "CREATE USER me WITH PASSWORD 'password';" -U postgres

script:
  - npm run test
after_success:
  - npm run coverage
