language: node_js
node_js:
  - stable

install: npm install
services:
  - postgresql

cache:
  directories:
    - node_modules

before_script:
  - 'CREATE DATABASE "Teamwork";' -U postgres
  - psql -c "CREATE USER Teawork WITH PASSWORD 'password';" -U postgres

script:
  - npm run test
